// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjfGvB85ZJoZzHe45IfKmJybHfhTZ51ew',
    appId: '1:432970850860:web:75ea1f342ac5d257fbe789',
    messagingSenderId: '432970850860',
    projectId: 'coffee-shop-57705',
    authDomain: 'coffee-shop-57705.firebaseapp.com',
    storageBucket: 'coffee-shop-57705.firebasestorage.app',
    measurementId: 'G-Q0C4RBCYQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHaqeXBk5ittZjoY6cftb-ioC1y6g0yeU',
    appId: '1:432970850860:android:5ddbf0a4e93d996ffbe789',
    messagingSenderId: '432970850860',
    projectId: 'coffee-shop-57705',
    storageBucket: 'coffee-shop-57705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDihOHsCrmt3iZ3tKLFNd7nr3P4k219RJI',
    appId: '1:432970850860:ios:2544485dcc58ed8afbe789',
    messagingSenderId: '432970850860',
    projectId: 'coffee-shop-57705',
    storageBucket: 'coffee-shop-57705.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDihOHsCrmt3iZ3tKLFNd7nr3P4k219RJI',
    appId: '1:432970850860:ios:2544485dcc58ed8afbe789',
    messagingSenderId: '432970850860',
    projectId: 'coffee-shop-57705',
    storageBucket: 'coffee-shop-57705.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjfGvB85ZJoZzHe45IfKmJybHfhTZ51ew',
    appId: '1:432970850860:web:768aa00b3e65c1d0fbe789',
    messagingSenderId: '432970850860',
    projectId: 'coffee-shop-57705',
    authDomain: 'coffee-shop-57705.firebaseapp.com',
    storageBucket: 'coffee-shop-57705.firebasestorage.app',
    measurementId: 'G-PQT7WKQVZB',
  );
}
